package day43_garbage_abstractClass;

public class C05_ChıldofAbstract extends C04{
    /*
    CLASSIMIZI BIR ABSTRACT CLASSIN CHILD I OLARAK BELIRTMEK ISTERSEK
    JAVA CLASS ISMININ ALTINI CIZER.

    BIZDEN
    CHILD CLASSI ABSTRACT YAPMAMIZI VEYA PARENT CLASSTAKI ABSTRACT CLASSLARI OVERRIDE ETMEMIZI ISTER
    PARENT OLAN ABSTRACT CLASSDAKI CONCRETE METHODLAR ISE OPSIYONELDIR
    ONLARI ISTERSEK OVERRIDE EDERIZ ,İSTEMEZSEK OVERRIDE ETMEYIZ

     */
    @Override
    public void absMethod() {

    }
}
